# Feature Scaling:

Feature scaling is a data preprocessing technique that standardizes the range of independent variables (features) in a dataset. This process ensures that all features contribute equally to the model's computations by bringing them to a similar scale, preventing features with larger numerical ranges from dominating others and improving model performance, especially for algorithms sensitive to feature magnitudes, such as gradient descent or distance-based algorithms. Common scaling methods include normalization (scaling to a fixed range, often 0-1) and standardization (scaling to a mean of 0 and a standard deviation of 1). 

- Why is Feature Scaling Important?
    - Prevents Feature Dominance: Without scaling, features with larger values (e.g., salary in thousands) can disproportionately influence the model compared to features with smaller values (e.g., age in tens), leading to poor performance. 
    - Improves Model Convergence: For algorithms like logistic regression and neural networks that use gradient descent, feature scaling helps them converge faster and more reliably. 
    - Enhances Algorithm Performance: Many algorithms, particularly those that rely on distance calculations (like K-Nearest Neighbors or K-Means), perform better when features are on a similar scale.

- Common Feature Scaling Methods:
    - Normalization (Min-Max Scaling): Transforms features to a specific range, usually between 0 and 1.
    - Standardization (Z-score Scaling): Rescales features so that they have a mean of 0 and a standard deviation of 1. This method is less affected by outliers than Min-Max scaling.

- When is Feature Scaling Needed?
    - Gradient-based algorithms: Linear Regression, Logistic Regression, and Neural Networks.
    - Distance-based algorithms: K-Nearest Neighbors (KNN) and Support Vector Machines (SVMs). 
    - Algorithms using Euclidean distance: K-Means Clustering.

- When is it NOT always necessary?
    - Tree-based algorithms: Decision Trees, Random Forests, and XGBoost are generally less affected by feature scaling. 
    - Algorithms that are not sensitive to scale: Some distance-agnostic algorithms.

#### Example:

In [8]:
import pandas as pd
from sklearn.preprocessing import StandardScaler, MinMaxScaler

In [2]:
df = pd.read_csv('boston.csv')

In [3]:
df.head()

,Unnamed: 0,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,Price
0,0,0.00632,18.0,2.31,0.0,0.538,6.575,65.2,4.0900,1.0,296.0,15.3,396.90,4.98,24.0
1,1,0.02731,0.0,7.07,0.0,0.469,6.421,78.9,4.9671,2.0,242.0,17.8,396.90,9.14,21.6
2,2,0.02729,0.0,7.07,0.0,0.469,7.185,61.1,4.9671,2.0,242.0,17.8,392.83,4.03,34.7
3,3,0.03237,0.0,2.18,0.0,0.458,6.998,45.8,6.0622,3.0,222.0,18.7,394.63,2.94,33.4
4,4,0.06905,0.0,2.18,0.0,0.458,7.147,54.2,6.0622,3.0,222.0,18.7,396.90,5.33,36.2

In [6]:
df = df.drop('Unnamed: 0', axis= 1)

In [7]:
df.head()

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,Price
0,0.00632,18.0,2.31,0.0,0.538,6.575,65.2,4.0900,1.0,296.0,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0.0,0.469,6.421,78.9,4.9671,2.0,242.0,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0.0,0.469,7.185,61.1,4.9671,2.0,242.0,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0.0,0.458,6.998,45.8,6.0622,3.0,222.0,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0.0,0.458,7.147,54.2,6.0622,3.0,222.0,18.7,396.90,5.33,36.2

In [15]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
CRIM,506.0,3.613524,8.601545,0.00632,0.082045,0.25651,3.677083,88.9762
ZN,506.0,11.363636,23.322453,0.00000,0.000000,0.00000,12.500000,100.0000
INDUS,506.0,11.136779,6.860353,0.46000,5.190000,9.69000,18.100000,27.7400
CHAS,506.0,0.069170,0.253994,0.00000,0.000000,0.00000,0.000000,1.0000
NOX,506.0,0.554695,0.115878,0.38500,0.449000,0.53800,0.624000,0.8710
RM,506.0,6.284634,0.702617,3.56100,5.885500,6.20850,6.623500,8.7800
AGE,506.0,68.574901,28.148861,2.90000,45.025000,77.50000,94.075000,100.0000
DIS,506.0,3.795043,2.105710,1.12960,2.100175,3.20745,5.188425,12.1265
RAD,506.0,9.549407,8.707259,1.00000,4.000000,5.00000,24.000000,24.0000
TAX,506.0,408.237154,168.537116,187.00000,279.000000,330.00000,666.000000,711.0000
PTRATIO,506.0,18.455534,2.164946,12.60000,17.400000,19.05000,20.200000,22.0000
B,506.0,356.674032,91.294864,0.32000,375.377500,391.44000,396.225000,396.9000
LSTAT,506.0,12.653063,7.141062,1.73000,6.950000,11.36000,16.955000,37.9700
Price,506.0,22.532806,9.197104,5.00000,17.025000,21.20000,25.000000,50.0000

##### 1) Standardization:

In [10]:
std_scaler = StandardScaler()
df_std_scaled = std_scaler.fit_transform(df)
df_std_scaled

array([[-0.41978194,  0.28482986, -1.2879095 , ...,  0.44105193,
        -1.0755623 ,  0.15968566],
       [-0.41733926, -0.48772236, -0.59338101, ...,  0.44105193,
        -0.49243937, -0.10152429],
       [-0.41734159, -0.48772236, -0.59338101, ...,  0.39642699,
        -1.2087274 ,  1.32424667],
       ...,
       [-0.41344658, -0.48772236,  0.11573841, ...,  0.44105193,
        -0.98304761,  0.14880191],
       [-0.40776407, -0.48772236,  0.11573841, ...,  0.4032249 ,
        -0.86530163, -0.0579893 ],
       [-0.41500016, -0.48772236,  0.11573841, ...,  0.44105193,
        -0.66905833, -1.15724782]])

In [11]:
df_std_scaled = pd.DataFrame(df_std_scaled, index= df.index, columns= df.columns)
df_std_scaled.head()

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,Price
0,-0.419782,0.284830,-1.287909,-0.272599,-0.144217,0.413672,-0.120013,0.140214,-0.982843,-0.666608,-1.459000,0.441052,-1.075562,0.159686
1,-0.417339,-0.487722,-0.593381,-0.272599,-0.740262,0.194274,0.367166,0.557160,-0.867883,-0.987329,-0.303094,0.441052,-0.492439,-0.101524
2,-0.417342,-0.487722,-0.593381,-0.272599,-0.740262,1.282714,-0.265812,0.557160,-0.867883,-0.987329,-0.303094,0.396427,-1.208727,1.324247
3,-0.416750,-0.487722,-1.306878,-0.272599,-0.835284,1.016303,-0.809889,1.077737,-0.752922,-1.106115,0.113032,0.416163,-1.361517,1.182758
4,-0.412482,-0.487722,-1.306878,-0.272599,-0.835284,1.228577,-0.511180,1.077737,-0.752922,-1.106115,0.113032,0.441052,-1.026501,1.487503

In [16]:
df_std_scaled.describe().T

,count,mean,std,min,25%,50%,75%,max
CRIM,506.0,-1.123388e-16,1.00099,-0.419782,-0.410970,-0.390667,0.007397,9.933931
ZN,506.0,7.898820e-17,1.00099,-0.487722,-0.487722,-0.487722,0.048772,3.804234
INDUS,506.0,2.106352e-16,1.00099,-1.557842,-0.867691,-0.211099,1.015999,2.422565
CHAS,506.0,-3.510587e-17,1.00099,-0.272599,-0.272599,-0.272599,-0.272599,3.668398
NOX,506.0,-1.965929e-16,1.00099,-1.465882,-0.913029,-0.144217,0.598679,2.732346
RM,506.0,-1.088282e-16,1.00099,-3.880249,-0.568630,-0.108466,0.482768,3.555044
AGE,506.0,-1.474446e-16,1.00099,-2.335437,-0.837448,0.317382,0.906798,1.117494
DIS,506.0,-8.425408e-17,1.00099,-1.267069,-0.805688,-0.279323,0.662371,3.960518
RAD,506.0,-1.123388e-16,1.00099,-0.982843,-0.637962,-0.523001,1.661245,1.661245
TAX,506.0,0.000000e+00,1.00099,-1.313990,-0.767576,-0.464673,1.530926,1.798194
PTRATIO,506.0,-4.212704e-16,1.00099,-2.707379,-0.488039,0.274859,0.806576,1.638828
B,506.0,-7.442444e-16,1.00099,-3.907193,0.205072,0.381187,0.433651,0.441052
LSTAT,506.0,-3.089316e-16,1.00099,-1.531127,-0.799420,-0.181254,0.603019,3.548771
Price,506.0,-5.195668e-16,1.00099,-1.908226,-0.599456,-0.145059,0.268523,2.989460

##### 2) Normalization:

In [12]:
minmax_scaler = MinMaxScaler()
df_minmax_scaled = minmax_scaler.fit_transform(df)
df_minmax_scaled

array([[0.00000000e+00, 1.80000000e-01, 6.78152493e-02, ...,
        1.00000000e+00, 8.96799117e-02, 4.22222222e-01],
       [2.35922539e-04, 0.00000000e+00, 2.42302053e-01, ...,
        1.00000000e+00, 2.04470199e-01, 3.68888889e-01],
       [2.35697744e-04, 0.00000000e+00, 2.42302053e-01, ...,
        9.89737254e-01, 6.34657837e-02, 6.60000000e-01],
       ...,
       [6.11892474e-04, 0.00000000e+00, 4.20454545e-01, ...,
        1.00000000e+00, 1.07891832e-01, 4.20000000e-01],
       [1.16072990e-03, 0.00000000e+00, 4.20454545e-01, ...,
        9.91300620e-01, 1.31070640e-01, 3.77777778e-01],
       [4.61841693e-04, 0.00000000e+00, 4.20454545e-01, ...,
        1.00000000e+00, 1.69701987e-01, 1.53333333e-01]])

In [13]:
df_minmax_scaled = pd.DataFrame(df_minmax_scaled, index= df.index, columns= df.columns)
df_minmax_scaled.head()

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,Price
0,0.000000,0.18,0.067815,0.0,0.314815,0.577505,0.641607,0.269203,0.000000,0.208015,0.287234,1.000000,0.089680,0.422222
1,0.000236,0.00,0.242302,0.0,0.172840,0.547998,0.782698,0.348962,0.043478,0.104962,0.553191,1.000000,0.204470,0.368889
2,0.000236,0.00,0.242302,0.0,0.172840,0.694386,0.599382,0.348962,0.043478,0.104962,0.553191,0.989737,0.063466,0.660000
3,0.000293,0.00,0.063050,0.0,0.150206,0.658555,0.441813,0.448545,0.086957,0.066794,0.648936,0.994276,0.033389,0.631111
4,0.000705,0.00,0.063050,0.0,0.150206,0.687105,0.528321,0.448545,0.086957,0.066794,0.648936,1.000000,0.099338,0.693333

In [17]:
df_minmax_scaled.describe().T

         count      mean       std  min       25%       50%       75%  max
CRIM     506.0  0.040544  0.096679  0.0  0.000851  0.002812  0.041258  1.0
ZN       506.0  0.113636  0.233225  0.0  0.000000  0.000000  0.125000  1.0
INDUS    506.0  0.391378  0.251479  0.0  0.173387  0.338343  0.646628  1.0
CHAS     506.0  0.069170  0.253994  0.0  0.000000  0.000000  0.000000  1.0
NOX      506.0  0.349167  0.238431  0.0  0.131687  0.314815  0.491770  1.0
RM       506.0  0.521869  0.134627  0.0  0.445392  0.507281  0.586798  1.0
AGE      506.0  0.676364  0.289896  0.0  0.433831  0.768280  0.938980  1.0
DIS      506.0  0.242381  0.191482  0.0  0.088259  0.188949  0.369088  1.0
RAD      506.0  0.371713  0.378576  0.0  0.130435  0.173913  1.000000  1.0
TAX      506.0  0.422208  0.321636  0.0  0.175573  0.272901  0.914122  1.0
PTRATIO  506.0  0.622929  0.230313  0.0  0.510638  0.686170  0.808511  1.0
B        506.0  0.898568  0.230205  0.0  0.945730  0.986232  0.998298  1.0
LSTAT    506.0  0.301409  0.197049  0.0  0.144040  0.265728  0.420116  1.0
Price    506.0  0.389618  0.204380  0.0  0.267222  0.360000  0.444444  1.0