# Feature Scaling:

Feature scaling is a machine learning preprocessing technique that standardizes numerical features to a common scale, preventing features with larger magnitudes from disproportionately influencing model outcomes and improving algorithm performance. 

Common scaling methods include Min-Max Scaling or Normalization, which rescales data to a specific range like 0 to 1, and Standardization (z-score scaling), which transforms features to have a mean of 0 and a standard deviation of 1. 

This process is vital for algorithms relying on distance calculations, such as k-means clustering, and for faster convergence in gradient-based optimization.

#### Why is Feature Scaling Necessary?
- Prevents Feature Dominance: Without scaling, features with large numerical values (e.g., income in thousands) can dominate those with smaller values (e.g., age in tens), even if the smaller-magnitude features are equally or more important to the model.

- Improves Algorithm Performance: Many machine learning algorithms, particularly those based on distance calculations (like SVM or KNN), are sensitive to feature scales. Scaling ensures that these algorithms can provide more accurate and reliable results. 

- Faster Convergence: For gradient-based algorithms, feature scaling can lead to faster convergence, as the optimization process can avoid the steep, elongated contours of the error surface that result from unscaled features.

In [39]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [40]:
# To Install Scikit-Learn:
# !pip install scikit-learn --user

# To Update Scikit-Learn to Latest Version if Already Installed:
# !pip install --upgrade scikit-learn --user

In [41]:
# Checking Version of Scikit-learn:

import sklearn
print(sklearn.__version__)

1.7.2

In [42]:
df = pd.read_csv('Churn_Modelling.csv')

In [43]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   RowNumber        10000 non-null  int64
 1   CustomerId       10000 non-null  int64
 2   Surname          10000 non-null  object
 3   CreditScore      10000 non-null  int64
 4   Geography        10000 non-null  object
 5   Gender           10000 non-null  object
 6   Age              10000 non-null  int64
 7   Tenure           10000 non-null  int64
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64
 10  HasCrCard        10000 non-null  int64
 11  IsActiveMember   10000 non-null  int64
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB

In [44]:
# Creating a Separate Dataframe with a COuple of Features Only:

new_df = pd.DataFrame(data= df, columns= ['Age', 'Tenure'])
new_df.head()

   Age  Tenure
0   42       2
1   41       1
2   42       8
3   39       1
4   43       2

In [45]:
new_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Age     10000 non-null  int64
 1   Tenure  10000 non-null  int64
dtypes: int64(2)
memory usage: 156.4 KB

In [46]:
new_df.describe()

                Age        Tenure
count  10000.000000  10000.000000
mean      38.921800      5.012800
std       10.487806      2.892174
min       18.000000      0.000000
25%       32.000000      3.000000
50%       37.000000      5.000000
75%       44.000000      7.000000
max       92.000000     10.000000

### 1) Normalization (Min-Max Scaling):

- How it works: Rescales features to a fixed range, most commonly between 0 and 1. 
- Formula: X_{scaled} = (X - X_min) / (X_max - X_min).
- Best for: Algorithms sensitive to the range of the features, like neural networks, or when a fixed range is desired. 
- Drawback: Can be sensitive to outliers, as the minimum and maximum values are used for the scaling.

In [47]:
from sklearn.preprocessing import MinMaxScaler

##### Small Example:

In [48]:
data = np.array([[2],[3],[5],[6],[6]])
print(data)
print(data.ndim)
print(data.shape)

[[2]
 [3]
 [5]
 [6]
 [6]]
2
(5, 1)

In [49]:
scaler = MinMaxScaler()
scaled_data = scaler.fit_transform(data)
print(scaled_data)

[[0.  ]
 [0.25]
 [0.75]
 [1.  ]
 [1.  ]]

##### Normalization of Features in Dataframe:

In [50]:
new_df.head()

   Age  Tenure
0   42       2
1   41       1
2   42       8
3   39       1
4   43       2

In [51]:
scaler = MinMaxScaler()
scaled_df = scaler.fit_transform(new_df)
print(scaled_df)
print(type(scaled_df))

[[0.32432432 0.2       ]
 [0.31081081 0.1       ]
 [0.32432432 0.8       ]
 ...
 [0.24324324 0.7       ]
 [0.32432432 0.3       ]
 [0.13513514 0.4       ]]
<class 'numpy.ndarray'>

In [52]:
# Turning Returned Array into Dataframe:

scaled_df = pd.DataFrame(data= scaled_df, columns= new_df.columns)
scaled_df.head()

        Age  Tenure
0  0.324324     0.2
1  0.310811     0.1
2  0.324324     0.8
3  0.283784     0.1
4  0.337838     0.2

In [53]:
print(scaled_df['Age'].max())
print(scaled_df['Age'].min())
print(scaled_df['Age'].mean())
print(scaled_df['Age'].std())

1.0000000000000002
0.0
0.282727027027027
0.14172711421222448

In [54]:
print(scaled_df['Tenure'].max())
print(scaled_df['Tenure'].min())
print(scaled_df['Tenure'].mean())
print(scaled_df['Tenure'].std())

1.0
0.0
0.5012800000000001
0.2892174377049684

### 2) Standardization (z-Score Scaling):

- How it works: Transforms features to have a mean of 0 and a standard deviation of 1. 
- Formula: X_{scaled} = (X - \mu)\ sigma, where mu is the mean and sigma is the standard deviation. 
- Best for: Algorithms that assume a normally distributed dataset or require zero-centered features, such as Principal Component Analysis (PCA).
- Benefit: Less affected by outliers compared to Min-Max Scaling.

In [55]:
from sklearn.preprocessing import StandardScaler

##### Small Example:

In [56]:
data = np.array([[2],[3],[5],[6],[6]])
print(data)
print(data.ndim)
print(data.shape)

[[2]
 [3]
 [5]
 [6]
 [6]]
2
(5, 1)

In [57]:
scaler = StandardScaler()
scaled_data = scaler.fit_transform(data)
print(scaled_data)

[[-1.47709789]
 [-0.86164044]
 [ 0.36927447]
 [ 0.98473193]
 [ 0.98473193]]

##### Standardization of Features in Dataframe:

In [58]:
new_df.head()

   Age  Tenure
0   42       2
1   41       1
2   42       8
3   39       1
4   43       2

In [59]:
scaler = StandardScaler()
scaled_df = scaler.fit_transform(new_df)
scaled_df

array([[ 0.29351742, -1.04175968],
       [ 0.19816383, -1.38753759],
       [ 0.29351742,  1.03290776],
       ...,
       [-0.27860412,  0.68712986],
       [ 0.29351742, -0.69598177],
       [-1.04143285, -0.35020386]])

In [60]:
# Turning Returned Array into Dataframe:

scaled_df = pd.DataFrame(data= scaled_df, columns= new_df.columns)
scaled_df.head()

        Age    Tenure
0  0.293517 -1.041760
1  0.198164 -1.387538
2  0.293517  1.032908
3  0.007457 -1.387538
4  0.388871 -1.041760

In [61]:
print(scaled_df['Age'].max())
print(scaled_df['Age'].min())
print(scaled_df['Age'].mean())
print(scaled_df['Age'].std())

5.0611969579618314
-1.9949687539344934
2.318145675417327e-16
1.0000500037503124

In [62]:
print(scaled_df['Tenure'].max())
print(scaled_df['Tenure'].min())
print(scaled_df['Tenure'].mean())
print(scaled_df['Tenure'].std())

1.7244635794717436
-1.7333154938995745
-1.078248601515952e-16
1.0000500037503124