# Regularization (Ridge, Lasso and Elastic-Net Regression)

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.preprocessing import StandardScaler, PolynomialFeatures
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression, Ridge, RidgeCV, Lasso, LassoCV, ElasticNet, ElasticNetCV
from sklearn.metrics import mean_squared_error, r2_score

In [2]:
df = pd.read_csv('Advertising.csv')

In [3]:
df.head()

   Unnamed: 0     TV  radio  newspaper  sales
0           1  230.1   37.8       69.2   22.1
1           2   44.5   39.3       45.1   10.4
2           3   17.2   45.9       69.3    9.3
3           4  151.5   41.3       58.5   18.5
4           5  180.8   10.8       58.4   12.9

In [4]:
df = df.drop('Unnamed: 0', axis= 1)

In [5]:
df.head()

      TV  radio  newspaper  sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3    9.3
3  151.5   41.3       58.5   18.5
4  180.8   10.8       58.4   12.9

In [6]:
df.describe()

               TV       radio   newspaper       sales
count  200.000000  200.000000  200.000000  200.000000
mean   147.042500   23.264000   30.554000   14.022500
std     85.854236   14.846809   21.778621    5.217457
min      0.700000    0.000000    0.300000    1.600000
25%     74.375000    9.975000   12.750000   10.375000
50%    149.750000   22.900000   25.750000   12.900000
75%    218.825000   36.525000   45.100000   17.400000
max    296.400000   49.600000  114.000000   27.000000

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   TV         200 non-null    float64
 1   radio      200 non-null    float64
 2   newspaper  200 non-null    float64
 3   sales      200 non-null    float64
dtypes: float64(4)
memory usage: 6.4 KB

##### Train Test Split:

In [8]:
# Separatting Features and Target:

X = df.drop('sales', axis= 1)
y = df['sales']

In [9]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size= 0.2, random_state= 42)

In [10]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(160, 3)
(40, 3)
(160,)
(40,)

##### Polynomial Features:

We will convert our Data into Polynomial  Features as increasing Features will make **Regularization Effects more visible**.

In [11]:
poly_features = PolynomialFeatures(degree= 3, include_bias= False)

In [12]:
# Converting Features of training and Test Data into Polynomial Features:

X_train_poly = poly_features.fit_transform(X_train)
X_test_poly = poly_features.transform(X_test)

In [13]:
print(X_train_poly.shape)
print(X_test_poly.shape)

(160, 19)
(40, 19)

##### Scaling:

In [14]:
# Scaling The Data:

scaler = StandardScaler()
X_train_poly = scaler.fit_transform(X_train_poly)
X_test_poly = scaler.transform(X_test_poly)

#### 1) Linear Regression Model:

In [15]:
lr_model = LinearRegression()
lr_model.fit(X_train_poly, y_train)

LinearRegression()

In [16]:
# Predictions Using Model:
y_pred_lr = lr_model.predict(X_test_poly)

In [17]:
y_pred_lr

array([17.11248517, 22.22545794, 21.48013597,  7.29194307, 24.25090325,
       13.12825544, 22.53973754,  8.60518861, 11.62323942, 15.52703964,
        7.67875377,  8.54547414, 12.15521933,  5.17285299, 10.50193485,
       12.095227  ,  6.40526398, 16.36097536, 11.22732048, 18.76103561,
       19.60776214, 11.62897333,  9.493112  , 21.78376471,  9.25708004,
        7.977186  , 22.1031492 , 12.81249392, 10.66311519,  5.21580322,
       11.21971089, 10.71494125, 22.71964779,  8.46157422, 16.18971107,
       20.84235212, 10.92054069, 20.73439222, 12.13257855,  6.43508762])

In [18]:
# Model Evaluation:

lr_model_rmse = np.sqrt(mean_squared_error(y_test, y_pred_lr))

print(f'RMSE: {lr_model_rmse}')
print(f'R2-Scoe: {r2_score(y_test, y_pred_lr)}')

RMSE: 0.5427415675039119
R2-Scoe: 0.9906674629185214

In [19]:
# Feature Coefficients:

print(lr_model.coef_)

[  7.7287509    0.15927822   0.49689685 -11.11254514   4.48112743
  -1.43128621   0.12624542   0.61923373  -0.05817057   5.24371878
  -0.92218692   1.0834731    0.39410125  -0.62578493   0.3423923
  -0.25719331  -0.0472515   -0.14657727  -0.18392269]

#### 2) Ridge (L2) Regression Model:

In [20]:
ridge_model = Ridge(alpha= 5)
ridge_model.fit(X_train_poly, y_train)

Ridge(alpha=5)

In [21]:
# Predictions Using Model:

y_pred_ridge = ridge_model.predict(X_test_poly)

In [22]:
y_pred_ridge

array([16.93263991, 22.70582918, 20.4654669 ,  8.27292666, 24.32333033,
       12.4527221 , 22.72852682,  8.5808278 , 12.26704228, 15.28301538,
        8.64858521,  8.33611088, 12.18903565,  7.53668337, 10.41205887,
       12.14632078,  7.66013025, 16.2206688 , 10.64628332, 18.7715856 ,
       20.11518726, 12.36240236, 10.11990541, 22.23122794,  8.98687829,
        7.88027982, 22.31894757, 12.30469156, 10.10197753,  7.56274938,
       11.72707865, 10.28077536, 23.47285703,  8.7643716 , 15.45753401,
       20.84045719, 11.26078471, 20.22751954, 11.48896607,  6.98261253])

In [23]:
# Model Evaluation:

print(f'RMSE: {np.sqrt(mean_squared_error(y_test, y_pred_ridge))}')
print(f'R2-Score: {r2_score(y_test, y_pred_ridge)}')

RMSE: 0.7762490927001869
R2-Score: 0.9809095675641224

In [24]:
# Feature Coefficients:

print(ridge_model.coef_)

[ 2.6807003   0.68785541  0.04402613 -0.01616565  2.0556435   0.34984197
  0.05176505  0.1462996  -0.08531908 -0.85868519  0.23648444 -0.70158101
  1.05470067  0.17498711  0.17590714 -0.27364506 -0.06449763 -0.05094855
  0.00560022]

Alpha value can be from 0 to +infinity.

So, How do we find best Alpha value?

We can Use Ridge CV (Cross Validation) and pass on multiple alpha values to build different models.

In [25]:
# RidgeCV Model:

ridge_cv_model = RidgeCV(alphas = (0.01, 0.1, 1, 5, 10, 25, 50, 100),
                        cv= 10,
                        scoring= 'r2')

In [26]:
ridge_cv_model.fit(X_train_poly, y_train)

RidgeCV(alphas=(0.01, 0.1, 1, 5, 10, 25, 50, 100), cv=10, scoring='r2')

In [27]:
# Alpha Value that Gives Best R2-Score:

ridge_cv_model.alpha_

0.1

In [28]:
# Best R2-Score Seen by Model:

ridge_cv_model.best_score_

0.9767856247043772

In [29]:
# Predictions Using The Model:

y_pred_ridge_cv = ridge_cv_model.predict(X_test_poly)

In [30]:
y_pred_ridge_cv

array([17.15971523, 22.57225465, 20.71842729,  7.554397  , 24.34238261,
       12.91758508, 22.68640503,  8.54846254, 11.8960452 , 15.54803328,
        7.81762977,  8.42746654, 12.34991699,  5.77557639, 10.50694151,
       12.1736318 ,  6.792656  , 16.4584527 , 11.04623325, 18.86793543,
       19.83086086, 11.55876378,  9.4398743 , 21.92958804,  9.03009551,
        7.86358924, 22.26589665, 12.72155562, 10.47823678,  5.75769966,
       11.45459767, 10.5618683 , 23.20575502,  8.33072856, 15.66207826,
       20.98318989, 10.61028879, 20.30704587, 11.94524866,  6.5283758 ])

In [31]:
# Model Evaluation:

print(f'RMSE: {np.sqrt(mean_squared_error(y_test, y_pred_ridge_cv))}')
print(f'R2-Score: {r2_score(y_test, y_pred_ridge_cv)}')

RMSE: 0.5976229585373606
R2-Score: 0.9886846471476035

#### 3) Lasso (L1) Regression Model:

In [32]:
lasso_model = Lasso(alpha= 1)
lasso_model.fit(X_train_poly, y_train)

Lasso(alpha=1)

In [33]:
# Predictions Using Model:

y_pred_lasso = lasso_model.predict(X_test_poly)

In [34]:
y_pred_lasso

array([15.94064892, 20.53977004, 20.27166367,  9.76126881, 22.28124538,
       12.57391981, 20.92190563, 10.23247925, 11.84182534, 14.7668592 ,
       10.28249404, 10.01327826, 11.98475333,  9.42763361, 10.67368567,
       12.00530847,  9.48883717, 15.64495587, 11.429837  , 17.97872413,
       18.83458239, 12.36039916, 11.12427176, 20.82927674, 10.45389079,
        9.76871906, 20.54355106, 12.47088155, 11.00781009,  9.52225766,
       11.40836934, 11.26481386, 21.09484082, 10.12385837, 15.60062747,
       19.69550328, 11.97893603, 19.71793212, 11.97871722,  9.48805936])

In [47]:
# Feature Coefficients:

print(lasso_model.coef_)

[0.69600691 0.         0.         0.         3.44893766 0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.        ]

In [35]:
# Model Evaluation:

print(f'RMSE: {np.sqrt(mean_squared_error(y_test, y_pred_lasso))}')
print(f'R2-Score: {r2_score(y_test, y_pred_lasso)}')

RMSE: 1.6030736324174035
R2-Score: 0.9185819874851251

Alpha value can be from 0 to +infinity.

So, How do we find best Alpha value?

We can Use Lasso CV (Cross Validation) and pass on multiple alpha values to build different models.

In [37]:
# LassoCV Model:

lasso_cv_model = LassoCV(cv= 10, random_state= 42, max_iter= 10000)
lasso_cv_model.fit(X_train_poly, y_train, )

LassoCV(cv=10, max_iter=10000, random_state=42)

In [41]:
# Alpha Value that Gives Best R2-Score:

lasso_cv_model.alpha_

0.004896890908273869

In [42]:
# Feature Coefficients:

lasso_cv_model.coef_

array([ 5.29331547,  0.37711646,  0.24408148, -5.22604765,  3.59277402,
       -0.31432803,  0.        ,  0.04571421,  0.        ,  1.66577679,
       -0.16252366, -0.        ,  0.19493873, -0.        ,  0.03219455,
       -0.        ,  0.        ,  0.        ,  0.        ])

In [38]:
# Predictions Using Model:

y_pred_lasso_cv = lasso_cv_model.predict(X_test_poly)

In [39]:
y_pred_lasso_cv

array([17.16473457, 22.60216805, 20.73970555,  7.43878239, 24.31744612,
       12.68116501, 22.69561019,  8.46448736, 11.94940694, 15.57272578,
        8.00224145,  8.38081806, 11.94551819,  6.10594692, 10.56070142,
       12.27510119,  6.63780915, 16.48166353, 10.8387883 , 18.89828184,
       20.00338273, 12.96127749,  9.70988491, 22.04023337,  9.08183388,
        7.86678822, 22.28401092, 12.69458995, 10.37843201,  6.19444185,
       11.52754457, 10.38886618, 23.27175071,  8.8543995 , 15.6107738 ,
       20.9320523 , 11.16950125, 20.34569379, 11.89652635,  6.58392563])

In [40]:
# Model Evaluation:

print(f'RMSE: {np.sqrt(mean_squared_error(y_test, y_pred_lasso_cv))}')
print(f'R2-Score: {r2_score(y_test, y_pred_lasso_cv)}')

RMSE: 0.5503330958638764
R2-Score: 0.9904045616984563

#### 4) Elastic-Net (L1 and L2) Regression:

In [43]:
en_model = ElasticNet(alpha= 1, l1_ratio= 0.5)
en_model.fit(X_train_poly, y_train)

ElasticNet(alpha=1)

In [48]:
# Feature Coefficients:

en_model.coef_

array([0.87088942, 0.28731618, 0.        , 0.34498388, 1.11494599,
       0.07207694, 0.11522471, 0.        , 0.        , 0.0097742 ,
       0.69345506, 0.        , 0.818339  , 0.2032666 , 0.        ,
       0.        , 0.        , 0.        , 0.        ])

In [44]:
# Predictions Using Model:

y_pred_en = en_model.predict(X_test_poly)

In [45]:
y_pred_en

array([15.58098453, 20.62032343, 20.53092592, 10.31519669, 21.8235888 ,
       12.49284492, 20.61639842, 10.07041225, 12.50417729, 14.33959203,
       10.29413984,  9.89911355, 13.06256569,  9.85415945, 10.9430528 ,
       12.14155363,  9.85465336, 15.1071806 , 11.1802728 , 17.44473584,
       18.95812568, 12.59146547, 11.3799518 , 21.18810673, 10.24982861,
        9.68380156, 20.28468294, 12.12706445, 10.79831785,  9.83830537,
       12.00417994, 11.00422084, 21.37189548, 10.85800445, 16.10586803,
       19.0385245 , 12.26452936, 20.00841808, 11.6145504 ,  9.34193833])

In [46]:
# Model Evaluation:

print(f'RMSE: {np.sqrt(mean_squared_error(y_test, y_pred_en))}')
print(f'R2-Score: {r2_score(y_test, y_pred_en)}')

RMSE: 1.7755304947753925
R2-Score: 0.9001220024929084

In [50]:
# Elastic NEt CV Model:

en_cv_model = ElasticNetCV(l1_ratio= [0.001, 0.1, 0.5, 0.7, 0.9, 0.95, 0.99, 1], 
                            eps= 0.001, cv= 10, max_iter= 1000000)

en_cv_model.fit(X_train_poly, y_train)

ElasticNetCV(cv=10, l1_ratio=[0.001, 0.1, 0.5, 0.7, 0.9, 0.95, 0.99, 1],
             max_iter=1000000)

In [51]:
# Alpha Chosen By Model:

en_cv_model.alpha_

0.004896890908273869

In [52]:
# L1_Ratio Chosen By Model:

en_cv_model.l1_ratio_

1.0

In [54]:
# Predictions Using Model:

y_pred_en_cv = en_cv_model.predict(X_test_poly)

In [55]:
y_pred_en_cv

array([17.16473457, 22.60216805, 20.73970555,  7.43878239, 24.31744612,
       12.68116501, 22.69561019,  8.46448736, 11.94940694, 15.57272578,
        8.00224145,  8.38081806, 11.94551819,  6.10594692, 10.56070142,
       12.27510119,  6.63780915, 16.48166353, 10.8387883 , 18.89828184,
       20.00338273, 12.96127749,  9.70988491, 22.04023337,  9.08183388,
        7.86678822, 22.28401092, 12.69458995, 10.37843201,  6.19444185,
       11.52754457, 10.38886618, 23.27175071,  8.8543995 , 15.6107738 ,
       20.9320523 , 11.16950125, 20.34569379, 11.89652635,  6.58392563])

In [56]:
# Model Evaluation:

print(f'RMSE: {np.sqrt(mean_squared_error(y_test, y_pred_en_cv))}')
print(f'R2-Score: {r2_score(y_test, y_pred_en_cv)}')

RMSE: 0.5503330958638764
R2-Score: 0.9904045616984563