# Post HOC Test - Tukey's HSD Test

Tukey's range test, also known as Tukey's test, Tukey method, Tukey's honest significance test, or Tukey's HSD (honestly significant difference) test, is a single-step multiple comparison procedure and statistical test. It can be used to find means that are significantly different from each other.

Tukey's test compares the means of every treatment to the means of every other treatment; that is, it applies simultaneously to the set of all pairwise comparisons.

### Example 1:

From mpg Dataset in Seaborn Library, Check if Miles Per Gallon (mpg) is different for 4 Cylinder Cars for USA, Japan and Europe.

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from statsmodels.stats.multicomp import pairwise_tukeyhsd

In [2]:
sns.get_dataset_names()

['anagrams',
 'anscombe',
 'attention',
 'brain_networks',
 'car_crashes',
 'diamonds',
 'dots',
 'dowjones',
 'exercise',
 'flights',
 'fmri',
 'geyser',
 'glue',
 'healthexp',
 'iris',
 'mpg',
 'penguins',
 'planets',
 'seaice',
 'taxis',
 'tips',
 'titanic']

In [3]:
mpg = sns.load_dataset("mpg")

In [4]:
mpg.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
0,18.0,8,307.0,130.0,3504,12.0,70,usa,chevrolet chevelle malibu
1,15.0,8,350.0,165.0,3693,11.5,70,usa,buick skylark 320
2,18.0,8,318.0,150.0,3436,11.0,70,usa,plymouth satellite
3,16.0,8,304.0,150.0,3433,12.0,70,usa,amc rebel sst
4,17.0,8,302.0,140.0,3449,10.5,70,usa,ford torino

In [5]:
mpg.shape

(398, 9)

In [6]:
mpg.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   mpg           398 non-null    float64
 1   cylinders     398 non-null    int64
 2   displacement  398 non-null    float64
 3   horsepower    392 non-null    float64
 4   weight        398 non-null    int64
 5   acceleration  398 non-null    float64
 6   model_year    398 non-null    int64
 7   origin        398 non-null    object
 8   name          398 non-null    object
dtypes: float64(4), int64(3), object(2)
memory usage: 28.1+ KB

In [7]:
mpg.describe()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year
count,398.000000,398.000000,398.000000,392.000000,398.000000,398.000000,398.000000
mean,23.514573,5.454774,193.425879,104.469388,2970.424623,15.568090,76.010050
std,7.815984,1.701004,104.269838,38.491160,846.841774,2.757689,3.697627
min,9.000000,3.000000,68.000000,46.000000,1613.000000,8.000000,70.000000
25%,17.500000,4.000000,104.250000,75.000000,2223.750000,13.825000,73.000000
50%,23.000000,4.000000,148.500000,93.500000,2803.500000,15.500000,76.000000
75%,29.000000,8.000000,262.000000,126.000000,3608.000000,17.175000,79.000000
max,46.600000,8.000000,455.000000,230.000000,5140.000000,24.800000,82.000000

Storing Data for all 4 Cylinders Car in Different Dataset.

In [8]:
df = mpg[mpg["cylinders"] == 4][["mpg","origin"]]

In [9]:
df

      mpg  origin
14   24.0   japan
18   27.0   japan
19   26.0  europe
20   25.0  europe
21   24.0  europe
..    ...     ...
393  27.0     usa
394  44.0  europe
395  32.0     usa
396  28.0     usa
397  31.0     usa

[204 rows x 2 columns]

##### Performing Tukey's HSD Test Using Statsmodels Library:

In [10]:
pairwise_tukeyhsd(endog = df["mpg"], groups = df["origin"], alpha=0.05)

In [11]:
result = pairwise_tukeyhsd(endog = df["mpg"], groups = df["origin"], alpha=0.05)

In [12]:
print(result)

Multiple Comparison of Means - Tukey HSD, FWER=0.05
====================================================
group1 group2 meandiff p-adj   lower   upper  reject
----------------------------------------------------
europe  japan   3.1845  0.003  0.9267  5.4423   True
europe    usa  -0.5708 0.8186 -2.8061  1.6644  False
 japan    usa  -3.7554 0.0002 -5.9382 -1.5726   True
----------------------------------------------------

**Seeing p-Values, We fail to Reject Null Hypothesis for Europe and USA (meaning means of Europe and USA are not significantlly
different).**

**Means of Japan and USA AND Japan and Europe are Significantlly Different as we can Reject The Null Hypothesis for these
comparisions.**

### Example 2:

In [13]:
machine_1 = [150, 151, 152, 152, 151, 150]
machine_2 = [153, 152, 148, 151, 149, 152]
machine_3 = [156, 154, 155, 156, 157, 155]

We need to Store all these Data in Single Data Frame

In [14]:
machine_df = pd.concat([pd.DataFrame(data = {"Machine" : "Machine 1", "Volume" : machine_1}),
                       pd.DataFrame(data = {"Machine" : "Machine 2", "Volume" : machine_2}),
                       pd.DataFrame(data = {"Machine" : "Machine 3", "Volume" : machine_3})])

In [15]:
machine_df

     Machine  Volume
0  Machine 1     150
1  Machine 1     151
2  Machine 1     152
3  Machine 1     152
4  Machine 1     151
5  Machine 1     150
0  Machine 2     153
1  Machine 2     152
2  Machine 2     148
3  Machine 2     151
4  Machine 2     149
5  Machine 2     152
0  Machine 3     156
1  Machine 3     154
2  Machine 3     155
3  Machine 3     156
4  Machine 3     157
5  Machine 3     155

Performing Tukey's HSD Test Using Statsmodels Library:

In [16]:
results = pairwise_tukeyhsd(endog= machine_df["Volume"], groups= machine_df["Machine"], alpha= 0.05)

In [17]:
print(results)

   Multiple Comparison of Means - Tukey HSD, FWER=0.05
=========================================================
  group1    group2  meandiff p-adj   lower  upper  reject
---------------------------------------------------------
Machine 1 Machine 2  -0.1667  0.976 -2.2277 1.8944  False
Machine 1 Machine 3      4.5 0.0001  2.4389 6.5611   True
Machine 2 Machine 3   4.6667 0.0001  2.6056 6.7277   True
---------------------------------------------------------

**Seeing p-Values, We fail to Reject Null Hypothesis for Machine 1 and Machine 2 (meaning means of Machine 1 and Machine 2 
are not significantlly different).**

**Means of Machine 1 and Machine 3 AND Machine 2 and Machine 3 are Significantlly Different as we can Reject The Null 
Hypothesis for these comparisions.**